### ISSUE TITLE
Using custom testEnvironment

### ISSUE THREAD

**Issue by mmarkelov** [jest-community/create-jest-runner#27]
Can I use custom testEnvironment with created runner?
Tried this:
**jest-config.js**:
```js
module.exports = {
    runner: './index.js',
    testEnvironment: './custom-env.js',
};
```

**custom-env**:
```js
const NodeEnvironment = require('jest-environment-node');

class CustomEnvironment extends NodeEnvironment {
    constructor(config) {
        super(config)
    }

    async setup() {
        console.log('Setup Test Environment.');
        await super.setup();
    }

    async teardown() {
        console.log('Teardown Test Environment.');
        await super.teardown()
    }

    runScript(script) {
        return super.runScript(script)
    }
}

module.exports = CustomEnvironment;
```

I got no output from my **CustomEnvironment**, but it's ok when I comment out **runner** option

**Comment by itlgit** [comment]
This applies to all test environments--it seems that using a custom runner defaults to Node as the environment, regardless of what's specified in testEnvironment. I tried
`"runner": "jest-runner-mocha",
"testEnvironment": "jsdom",`
because my existing Mocha tests need to render to the DOM, but it fails with, "document is not defined."

**Comment by SimenB** [comment]
I'm getting `https://artifacthub-phx.oci.oraclecorp.com/api/npm/npmjs-registry/css.escape/-/css.escape-1.5.1.tgz: getaddrinfo ENOTFOUND artifacthub-phx.oci.oraclecorp.com` trying to install that repo 😅

**Comment by SimenB** [comment]
Removing the lockfile works 👍 

---

Anyways, the issue here is that it's up to the runner to set up the test env - meaning the bug you're seeing is in the mocha runner. You can see Jest's default runner loads the test env specified: https://github.com/facebook/jest/blob/98f10e698ae986c19fef2d8117be2341bcfb8f7f/packages/jest-runner/src/runTest.ts#L109-L110

Could have figured that put last time, sorry about that.

**Comment by itlgit** [comment]
😳Whoops! Sorry, should've scrubbed that lock file.
Anyways, thanks for the explanation.
